services:
  registry:
    image: mittwald/registry:3
    environment:
      REGISTRY_USER: ${REGISTRY_USER}
      REGISTRY_PASSWORD: ${REGISTRY_PASSWORD}
    ports:
      - '5000:5000'
    volumes:
      - registry-data:/var/lib/registry
volumes:
  registry-data:
